import LinkedList from './linked-list.js'

// Tests
const list = new LinkedList()
list.append(1)
list.append(10)
list.append(12)
list.append(100)
list.append(2)
console.log(JSON.stringify(list))
console.log('head:', list.headE())
console.log('size:', list.size())
console.log('tail:', list.tail())
console.log('index:', list.at(0))
console.log('index:', list.at(1))
console.log('index:', list.at(2))
console.log('index:', list.at(3))
console.log('index:', list.at(4))
console.log('index:', list.at(5))
console.log('pop', JSON.stringify(list.pop()))
console.log(JSON.stringify(list))
list.append(20)
console.log(list.contains(12))
console.log(list.contains(120))
console.log(list.find(12))
console.log(list.toString())
